version: '3.3'
services:
  kubetables:
    image: "sers-dev/kubetables:latest"
    build:
      context: "../"
      dockerfile: "./docker/Dockerfile"
    container_name: kubetables
    volumes:
      - "${KUBECONFIGPATH}:/root/.kube/"
    command:
      - "-c"
      - "/root/.kube/config"
    cap_add:
      - "NET_ADMIN"
    network_mode: "host"